### ISSUE TITLE
Standart example of scheme language isn't compiled.

### ISSUE THREAD

**Issue by aleus** [glycerine/go-capnproto#24]
I can't compile example of schema language from [official capnp's site](http://kentonv.github.io/capnproto/language.html). Capnp compiler return 
_"panic: missing package declaration for experiment.capnp:Date"_
Here is **experiment.capnp**:

```
@0x86c362fe6eec88f7;

struct Person {
  name @0 :Text;
  birthdate @3 :Date;

  email @1 :Text;
  phones @2 :List(PhoneNumber);

  struct PhoneNumber {
    number @0 :Text;
    type @1 :Type;

    enum Type {
      mobile @0;
      home @1;
      work @2;
    }
  }
}

struct Date {
  year @0 :Int16;
  month @1 :UInt8;
  day @2 :UInt8;
}
```

**Comment by majek** [comment]
It's very hard to read this error message. I found out that this didn't work for me:

    using Go = import "go.capnp";

While this did:

    using Go = import "src/github.com/glycerine/go-capnproto/aircraftlib/go.capnp";
